/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wjy_myapplication_aa */

#ifndef _Included_com_example_wjy_myapplication_aa
#define _Included_com_example_wjy_myapplication_aa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wjy_myapplication_aa
 * Method:    HelloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wjy_myapplication_aa_HelloJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
