/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <com_example_wjy_myapplication_aa.h>
/* Header for class com_example_wjy_myapplication_aa */
#include <jni.h>
#ifndef _Included_com_example_wjy_myapplication_aa
#define _Included_com_example_wjy_myapplication_aa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wjy_myapplication_aa
 * Method:    HelloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wjy_myapplication_aa_HelloJNI
  (JNIEnv * env, jclass object){

	char* cstr = "小景正在调用JNI";
	//把C字符串转换成java字符串
	//jstring     (*NewStringUTF)(JNIEnv*, const char*);
	jstring jstr = (*env)->NewStringUTF(env, cstr);
	return jstr;
  }

#ifdef __cplusplus
}
#endif
#endif
